version: 2.1

orbs:
   win: circleci/windows@2.4.0

workflows:
  test:
    jobs:
      # CircleCI's current generation of Node images, cimg/node, allow you to leave the
      # patch version unpinned, but require you to specify the minor version. The one
      # exception is cimg/node:current, which will always give us the latest release in
      # the latest major version-- and the latest major version is where it's most likely
      # that there would be a new minor version, anyway.
      - build-test-linux:
          name: latest Node version
          docker-image: cimg/node:current
          run-lint: true
      - build-test-linux:
          name: Node 18.10
          docker-image: cimg/node:18.10
      - build-test-linux:
          name: Node 16.14
          docker-image: cimg/node:16.17
      - build-test-linux:
          name: Node 14.19
          docker-image: cimg/node:14.20
      - build-test-windows:
          name: Windows

jobs:
  build-test-linux:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: false
      run-contract-tests:
        type: boolean
        default: true

    docker:
      - image: <<parameters.docker-image>>

    environment:
      NODE_ENV: test

    steps:
      - checkout
      - run: echo "Node version:" `node --version`
      
      - run: npm install

      - run: npm run test

      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: npm run lint:all
            - run: npm run check-typescript

      - when:
          condition: <<parameters.run-contract-tests>>
          steps:
            - run:
                name: start contact test service
                command: npm run contract-test-service
                background: true
            - run:
                name: run contract tests
                command: |
                  mkdir -p reports/junit
                  TEST_HARNESS_PARAMS="-junit reports/junit/contract-test-results.xml" npm run contract-test-harness

      - run:
          name: dependency audit
          command: ./scripts/better-audit.sh

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  build-test-windows:
    executor:
      name: win/default
      shell: powershell.exe

    environment:
      NODE_ENV: test

    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm test
