version: 2.1

orbs:
   win: circleci/windows@1.0.0

workflows:
  test:
    jobs:
      - build-test:
          name: current Node
          docker-image: circleci/node:latest
          with-lint: true
      - build-test:
          name: oldest supported Node
          docker-image: circleci/node:6
          with-lint: false

jobs:
  build-test:
    parameters:
      docker-image:
        type: string
      with-lint:
        type: boolean
        default: false

    docker:
      - image: <<parameters.docker-image>>

    steps:
      - checkout
      - run: echo "Node version:" `node --version`
      
      - run: npm install

      - run:
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

      - when:
          condition: <<parameters.with-lint>>
          steps:
            - run: npm run lint:all
            - run: npm run check-typescript

      - run:
          name: dependency audit
          command: ./scripts/better-audit.sh

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
